{"success": true, "error": "", "results": [{"severity_name": "HIGH", "pattern_name": "External call in loop", "description": "If a single call in the loop fails or revers, it will cause all other calls to fail as well.", "type": "Violation", "contentline": 32, "charnumber": 37}, {"severity_name": "HIGH", "pattern_name": "External call in loop", "description": "If a single call in the loop fails or revers, it will cause all other calls to fail as well.", "type": "Violation", "contentline": 33, "charnumber": 31}, {"severity_name": "HIGH", "pattern_name": "External call in loop", "description": "If a single call in the loop fails or revers, it will cause all other calls to fail as well.", "type": "Violation", "contentline": 35, "charnumber": 36}, {"severity_name": "MEDIUM", "pattern_name": "No-Ether-Involved Reentrancy", "description": "Reentrancy that involves no ether", "type": "Warning", "contentline": 33, "charnumber": 31}, {"severity_name": "MEDIUM", "pattern_name": "No-Ether-Involved Reentrancy", "description": "Reentrancy that involves no ether", "type": "Warning", "contentline": 35, "charnumber": 36}, {"severity_name": "MEDIUM", "pattern_name": "No-Ether-Involved Reentrancy", "description": "Reentrancy that involves no ether", "type": "Violation", "contentline": 32, "charnumber": 37}, {"severity_name": "HIGH", "pattern_name": "Unhandled Exception", "description": "The return value of statements that may return error values must be explicitly checked.", "type": "Warning", "contentline": 33, "charnumber": 31}, {"severity_name": "HIGH", "pattern_name": "Unhandled Exception", "description": "The return value of statements that may return error values must be explicitly checked.", "type": "Violation", "contentline": 35, "charnumber": 36}, {"severity_name": "MEDIUM", "pattern_name": "Unused Return Pattern", "description": "The value returned by an external function call is never used", "type": "Violation", "contentline": 35, "charnumber": 36}]}