{"success": false, "error": "Traceback (most recent call last):\n  File \"securify/__main__.py\", line 290, in main\n    matches.extend(pattern.find_matches())\n  File \"/home/smartcontract/SmartContract/securify2-master/securify/analyses/patterns/static/static_analysis_patterns.py\", line 73, in find_matches\n    static = analysis_context.static_analysis\n  File \"/home/smartcontract/SmartContract/securify2-master/securify/analyses/analysis.py\", line 88, in static_analysis\n    self._static = self.config.static_analysis(self)\n  File \"securify/__main__.py\", line 268, in <lambda>\n    static_analysis=lambda t: static_analysis.analyze_cfg(t.cfg, **souffle_config),\n  File \"/home/smartcontract/SmartContract/securify2-master/securify/staticanalysis/static_analysis.py\", line 124, in analyze_cfg\n    souffle_kwargs=kw_args_souffle)\n  File \"/home/smartcontract/SmartContract/securify2-master/securify/staticanalysis/souffle/souffle.py\", line 62, in run_souffle\n    **(souffle_kwargs or {}))\n  File \"/home/smartcontract/SmartContract/securify2-master/securify/staticanalysis/souffle/wrapper.py\", line 141, in souffle_wrapper\n    stderr_data=codecs.decode(stderrdata),\nsecurify.staticanalysis.souffle.exceptions.SouffleError: Error during souffle execution:  \n\nError loading data: Cannot open fact file arrayPush.facts\n\nError loading data: Cannot open fact file balance.facts\n\nError loading data: Cannot open fact file builtinFunction.facts\n\nError loading data: Cannot open fact file mapLoad.facts\n\nError loading data: Cannot open fact file uop.facts\n\n\n", "results": []}